export const dynamic = "force-static";

import { CodePanel } from "@/components/ui/code-panel";
import { CodeTabs } from "@/components/ui/code-tabs";

export default function ThemingPage() {
  return (
    <main className="container">
      <h1>테마 커스터마이징</h1>
      <p className="muted">
        sh-ui 토큰을 프로젝트에 맞게 바꾸는 방법. 쉬운 것부터 깊이 있는 것까지.
      </p>

      <h2>1. sh-ui.config.json 3축</h2>
      <p>
        가장 가벼운 커스터마이징. <code>base</code>, <code>radius</code>, <code>mode</code> 값을 바꾼 뒤 <code>npx sh-ui-cli add tokens</code>로 재생성하면 전체 토큰이 새 값으로 갱신된다.
      </p>
      <CodePanel
        language="json"
        filename="sh-ui.config.json"
        code={`{
  "theme": {
    "base": "zinc",          // neutral → zinc / slate (grayscale 톤)
    "radius": "lg",          // md → lg (전체 radius 확대)
    "mode": "light-dark"     // 다크 분기 유지
  }
}`}
      />
      <p className="muted">
        base / radius / mode는 <strong>프리셋 스위치</strong>다. 더 세밀한 제어는 아래 방법 사용.
      </p>

      <h2>2. CSS 변수 오버라이드 (React)</h2>
      <p>
        생성된 <code>tokens.css</code>를 직접 열어 필요한 변수만 덮어쓴다. <code>tokens.css</code>는 <strong>당신 것</strong>이다 — shadcn 방식이라 재생성 없이 수정 가능.
      </p>
      <CodePanel
        language="css"
        filename="app/styles/tokens.css"
        code={`:root {
  /* 생성된 값 */
  --primary: #171717;
  --primary-hover: #262626;

  /* 브랜드 컬러로 덮어쓰기 */
  --primary: #7C3AED;         /* Violet 600 */
  --primary-hover: #6D28D9;   /* Violet 700 */
  --primary-foreground: #FFFFFF;
}

.dark {
  --primary: #A78BFA;         /* Violet 400 */
  --primary-hover: #C4B5FD;
}`}
      />
      <p className="muted">
        팁: 생성된 값 바로 아래에 오버라이드를 두면 "어느 것이 원본이고 어느 것이 커스텀인지" 분명해진다.
      </p>

      <h2>3. Flutter ShUiTheme copyWith</h2>
      <p>
        Flutter는 <code>sh_ui_tokens.dart</code>를 직접 수정하거나, <code>MaterialApp</code>에 등록할 때 <code>copyWith</code>로 덮어쓴다. 재생성해도 살아남는 오버라이드를 원하면 <code>copyWith</code>를 권장.
      </p>
      <CodeTabs
        items={[
          {
            value: "copywith",
            label: "copyWith",
            language: "dart",
            filename: "main.dart",
            code: `final customColors = ShUiColorTokens.light.copyWith(
  // light 모드 기본값을 가져온 뒤 primary만 브랜드 컬러로
);

final customLight = ShUiTheme.light.copyWith(
  colors: const ShUiColorTokens(
    background: Color(0xFFFFFFFF),
    backgroundSubtle: Color(0xFFFAFAFA),
    backgroundMuted: Color(0xFFF5F5F5),
    backgroundInverse: Color(0xFF0A0A0A),
    foreground: Color(0xFF0A0A0A),
    foregroundMuted: Color(0xFF737373),
    foregroundSubtle: Color(0xFFA3A3A3),
    foregroundInverse: Color(0xFFFFFFFF),
    border: Color(0xFFE5E5E5),
    borderStrong: Color(0xFFD4D4D4),
    primary: Color(0xFF7C3AED),          // ← 브랜드 컬러
    primaryForeground: Color(0xFFFFFFFF),
    primaryHover: Color(0xFF6D28D9),     // ← 호버
    danger: Color(0xFFEF4444),
    dangerForeground: Color(0xFFFFFFFF),
  ),
);

MaterialApp(
  theme: ThemeData(extensions: [customLight]),
  // ...
);`,
          },
          {
            value: "direct",
            label: "파일 직접 수정",
            language: "dart",
            filename: "lib/foundation/sh_ui_tokens.dart",
            code: `// 주석 "Generated by @sh-ui/tokens" 무시하고 값을 바꾸면 됨.
// 단, 재생성(npx sh-ui-cli add tokens) 시 덮어쓰니 config.json으로
// 관리 가능한 건 1번 방법으로.

static const light = ShUiColorTokens(
  // ...
  primary: Color(0xFF7C3AED),
  primaryHover: Color(0xFF6D28D9),
  // ...
);`,
          },
        ]}
      />

      <h2>4. 스코프 기반 테마 (일부 영역만 다른 색)</h2>
      <p>
        대시보드 안에서 특정 섹션만 다른 primary를 쓰고 싶다면, 부모에 클래스/CSS 변수를 한정해서 토큰을 덮는다.
      </p>
      <CodePanel
        language="css"
        code={`/* tokens.css 또는 컴포넌트 CSS */
.promo-section {
  --primary: #EC4899;           /* 해당 섹션 내부에서만 pink */
  --primary-hover: #DB2777;
  --radius: 1rem;               /* 더 둥근 카드 느낌 */
}`}
      />
      <CodePanel
        language="tsx"
        code={`<div className="promo-section">
  <Button>이벤트 참여하기</Button>    {/* pink primary */}
</div>

<Button>일반 액션</Button>              {/* 원래 primary */}`}
      />
      <p className="muted">
        CSS 변수는 자식에게 캐스케이드된다. 컴포넌트 코드는 한 줄도 수정 안 하고 스코프 내부만 테마가 바뀐다.
      </p>

      <h2>5. 레시피 — 브랜드 컬러 전면 적용</h2>
      <p>
        Violet(보라) 기반 브랜드로 바꾸는 최소 diff.
      </p>
      <CodePanel
        language="css"
        filename="app/styles/tokens.css"
        code={`:root {
  --primary: #7C3AED;
  --primary-hover: #6D28D9;
  --primary-foreground: #FFFFFF;
}
.dark {
  --primary: #A78BFA;
  --primary-hover: #C4B5FD;
  --primary-foreground: #1E1B4B;
}`}
      />

      <h2>6. 레시피 — 컴팩트 UI</h2>
      <p>
        control 높이와 spacing을 한 단계 줄여 정보 밀도 올리기.
      </p>
      <CodePanel
        language="css"
        code={`:root {
  /* 40/32/48 → 36/28/44로 한 단계씩 줄이기 */
  --control-sm: 28px;
  --control-md: 36px;
  --control-lg: 44px;

  /* padding 줄이기 */
  --space-3: 10px;   /* 12 → 10 */
  --space-4: 14px;   /* 16 → 14 */
}`}
      />
      <p className="muted">
        <strong>주의</strong>: 스케일을 통째로 덮으면 이미 해당 토큰을 쓰는 모든 컴포넌트가 영향을 받는다. 특정 컴포넌트만 줄이려면 스코프 방식을 사용.
      </p>

      <h2>7. 레시피 — 커스텀 폰트 스케일</h2>
      <p>
        기본 스케일(12/14/16/18/20/24)이 작다면 전체 한 단계 올리기.
      </p>
      <CodePanel
        language="css"
        code={`:root {
  --text-xs:   13px;
  --text-sm:   15px;
  --text-base: 17px;
  --text-lg:   19px;
  --text-xl:   22px;
  --text-2xl:  26px;
}`}
      />
      <p>
        Flutter에서 같은 변경을 하려면 <code>ShUiTextTokens</code>를 직접 만든 뒤 <code>ShUiTheme.light.copyWith(text: customText)</code>로 끼워 넣는다.
      </p>

      <h2>8. base64 테마 코드 — 손본 톤 영구 보관</h2>
      <p>
        2~7번으로 손본 토큰을 다음 스캐폴드까지 그대로 가져가고 싶다면 base64 테마 코드로 박제. 프리셋(<code>neutral</code> 등)으로 표현 못 하는 커스텀 톤(개별 색, spacing, typography)을 손실 없이 한 문자열에 담는다. 같은 코드를 <code>sh_ui_create_project</code> 의 <code>theme</code> 인자나 CLI <code>--theme</code> 플래그에 넣으면 다음 프로젝트가 동일 톤으로 재현된다.
      </p>
      <CodeTabs
        items={[
          {
            value: "playground",
            label: "플레이그라운드 export",
            language: "bash",
            code: `# /create 에서 토큰 시각 편집 → "프로젝트 생성" 다이얼로그가
# 아래 명령을 자동 합성. --theme 뒤 문자열이 base64 테마 코드.
npx sh-ui-cli create my-app \\
  --platform next --structure standalone \\
  --theme 'eyJsaWdodCI6...'`,
          },
          {
            value: "mcp-encode",
            label: "MCP encode",
            language: "ts",
            code: `// AI 에게 "이 톤 base64 로 저장해줘" → sh_ui_encode_theme 호출.
// 입력: { light, dark, radius, (선택) success/warning/info ... }
// 출력: "eyJsaWdodCI6..." (base64 한 문자열)
//
// 그 base64 를 sh_ui_create_project 의 theme 인자에 넘기면
// 다음 프로젝트가 같은 톤으로 스캐폴드된다 (프리셋 자리에 그대로).`,
          },
          {
            value: "roundtrip",
            label: "round-trip 수정",
            language: "ts",
            code: `// 기존 base64 의 일부만 손보고 싶을 때:
// 1. sh_ui_decode_theme("eyJsaWdodCI6...") → 토큰 객체
// 2. 객체에서 필요한 키만 변경 (예: light.primary 만 새 색)
// 3. sh_ui_encode_theme(<수정된 객체>) → 새 base64
//
// 매번 처음부터 다시 만들 필요 없음.`,
          },
          {
            value: "external",
            label: "외부 디자인 import",
            language: "ts",
            code: `// 디자이너가 Figma / 브랜드 가이드 / 다른 DS 토큰을 가져온 경우.
// 형태 자유 — hex 묶음, design tokens JSON, Tailwind config 등.
//
// 사용자: "primary #7C3AED, accent #EC4899, dark 모드 primary #A78BFA,
//          radius 0.75rem 으로 sh-ui base64 만들어줘"
//
// AI 가 내부적으로:
// 1. neutral 같은 베이스 프리셋을 깔고
// 2. 위에서 받은 키만 덮어쓴 뒤 (빠진 background/border 등 자동 채움)
// 3. sh_ui_encode_theme 으로 인코딩 → "eyJsaWdodCI6..."
//
// 그 base64 를 sh_ui_create_project 의 theme 에 넣으면 처음부터
// 디자이너 톤으로 스캐폴드된다 — tokens.css 후편집 불필요.`,
          },
        ]}
      />
      <p className="muted">
        프리셋 이름(<code>neutral</code> / <code>slate</code> / ...)과 base64 둘 다 <code>theme</code> 슬롯에 들어가며 길이로 자동 판별. 옵셔널 색 토큰(<code>success</code> / <code>warning</code> / <code>info</code> + <code>-foreground</code>)도 같이 인코딩되지만 light / dark 양쪽 다 정의된 경우에만 CSS 로 emit — 한쪽만 있으면 컴포넌트 fallback 이 깨질 수 있어 안전 가드. (v0.55.0+)
      </p>

      <p>
        <strong>워크플로 — AI 경유 (MCP)</strong>
      </p>
      <p>
        AI 어시스턴트와 MCP 가 붙어 있다면 4 단계를 자연어로 한 번에 위임할 수 있다 — 사용자는 base64 문자열을 직접 만지지 않는다. <strong>AI 가 없거나 직접 만들고 싶다면</strong> 아래 §9 의 <em>"AI 없이 base64 만들기"</em> 참조 — 같은 산출물을 <code>/create</code> 플레이그라운드 / Node 한 줄 / 브라우저 콘솔 어느 쪽으로도 만들 수 있다.
      </p>
      <ol>
        <li>
          AI 가 <code>tokens.css</code> 의 <code>:root</code> / <code>.dark</code> 블록 색만 편집 (생성 마커 <code>/* sh-ui:tokens:* */</code> 는 건드리지 않음 — 다음 <code>add tokens</code> 에서 안전하게 재생성되도록).
        </li>
        <li>
          AI 가 <code>sh_ui_encode_theme</code> 으로 <code>{`{ light, dark, radius }`}</code> 객체를 base64 로 인코딩. 옵셔널 색 토큰(<code>success</code> / <code>warning</code> / <code>info</code>)도 함께 가능.
        </li>
        <li>
          base64 를 사용자에게 한 번 보여주고 (대화 메모리에도 보관) — 이게 톤의 단일 진실 소스가 된다.
        </li>
        <li>
          다음 <code>sh_ui_create_project</code> 호출 시 <code>theme</code> 인자에 그 base64 를 그대로 — 같은 프로젝트를 재생성해도 톤이 살아남는다.
        </li>
      </ol>
      <p className="muted">
        부분 수정은 round-trip 으로: <code>sh_ui_decode_theme</code> → 객체에서 필요한 키만 바꿈 → <code>sh_ui_encode_theme</code>. AI 가 한 턴 안에 처리하므로 사용자는 "primary 만 좀 더 채도 낮춰줘" 같이 자연어로 지시하면 된다.
      </p>

      <p>
        <strong>외부 디자인 가져오기 — 디자이너 톤을 sh-ui 로 import</strong>
      </p>
      <p>
        Figma 의 design tokens, 브랜드 가이드의 hex 팔레트, 다른 디자인 시스템 export — 형식은 자유. AI 한테 그대로 던지면 sh-ui 토큰 shape 으로 매핑한 뒤 base64 로 박제한다. 핵심 스키마는 <strong>light/dark 각 15개 필수 색 토큰</strong>(<code>background</code> / <code>foreground</code> / <code>primary</code> / <code>border</code> / <code>danger</code> 계열) + <code>radius</code>. 디자이너가 일부만 가져왔어도 빠진 키는 가장 가까운 프리셋(<code>neutral</code> / <code>slate</code> 등)에서 자동으로 채워 검증을 통과시킨다.
      </p>
      <CodePanel
        language="md"
        filename="대화 흐름 예시"
        code={`# 1. 디자이너가 톤을 들고 옴 (Figma export, 브랜드 hex 리스트, 무엇이든)
사용자: 우리 브랜드 컬러야:
        - primary #7C3AED, primary-hover #6D28D9, primary-foreground #FFFFFF
        - accent #EC4899
        - danger #EF4444
        - radius 0.75rem
        - 다크 모드는 primary #A78BFA, primary-hover #C4B5FD

        sh-ui base64 만들어줘.

# 2. AI 가 빠진 키(background/foreground/border 계열)를 neutral 에서 채우고
#    light/dark 양쪽 15키 충족 검증 → encodeTheme

AI:    ✓ 인코딩 완료. 다음 명령으로 처음부터 그 톤으로 스캐폴드:

       npx sh-ui-cli create my-app --platform next --structure standalone \\
         --theme 'eyJsaWdodCI6...'

       또는 sh_ui_create_project 의 theme 인자에 위 base64 그대로.`}
      />
      <p className="muted">
        옵셔널 색 토큰 6개(<code>success</code> / <code>warning</code> / <code>info</code> + 각 <code>-foreground</code>)는 <strong>light/dark 양쪽 다 정의된 경우에만</strong> 인코딩에 포함 — 한쪽만 있으면 컴포넌트 fallback 이 깨질 수 있어 안전 가드. 디자이너가 한쪽만 줬다면 AI 가 빠진 쪽을 한 번 더 묻거나 베이스 프리셋 값으로 채운다.
      </p>
      <p className="muted">
        Figma <em>Design Tokens</em> 플러그인 export (W3C DTCG JSON) 도 그대로 첨부 가능 — 키 이름이 sh-ui shape 과 다를 때 AI 가 의미 매핑(<code>color/brand/primary</code> → <code>primary</code> 등). 모호한 키는 사용자에게 한 번 확인.
      </p>

      <h2>9. 케이스별 입력 예제 — 어디까지 채울 수 있나</h2>
      <p>
        <code>sh_ui_encode_theme</code> 입력은 <strong>필수 3 필드</strong>(<code>light</code> / <code>dark</code> / <code>radius</code>) 위에 옵셔널 카테고리를 더하는 구조다. 아래 4 케이스는 가장 가벼운 형태부터 풀스택까지 — 각 케이스의 입력 JSON 과 실제 인코딩 결과 base64 를 짝으로 보여준다. 그대로 복붙해 <code>--theme</code> 또는 <code>sh_ui_create_project</code> 의 <code>theme</code> 인자에 넣어 검증해볼 수 있다.
      </p>

      <h3>케이스 A — 필수만 (15 + 15 + radius)</h3>
      <p>
        가장 단순한 형태. <code>light</code> / <code>dark</code> 각 15 색 토큰 + <code>radius</code> 한 개. 색만 손보고 spacing/typography 같은 메트릭은 디폴트로 두고 싶을 때.
      </p>
      <CodeTabs
        items={[
          {
            value: "input",
            label: "입력 객체",
            language: "ts",
            filename: "encodeTheme(input)",
            code: `{
  light: {
    'background': '#FFFFFF',
    'background-subtle': '#FAFAFA',
    'background-muted': '#F5F5F5',
    'background-inverse': '#0A0A0A',
    'foreground': '#0A0A0A',
    'foreground-muted': '#525252',
    'foreground-subtle': '#A3A3A3',
    'foreground-inverse': '#FFFFFF',
    'border': '#E5E5E5',
    'border-strong': '#D4D4D4',
    'primary': '#7C3AED',
    'primary-foreground': '#FFFFFF',
    'primary-hover': '#6D28D9',
    'danger': '#DC2626',
    'danger-foreground': '#FFFFFF',
  },
  dark: {
    'background': '#0A0A0A',
    'background-subtle': '#171717',
    'background-muted': '#262626',
    'background-inverse': '#FFFFFF',
    'foreground': '#FAFAFA',
    'foreground-muted': '#A3A3A3',
    'foreground-subtle': '#737373',
    'foreground-inverse': '#0A0A0A',
    'border': '#262626',
    'border-strong': '#404040',
    'primary': '#A78BFA',
    'primary-foreground': '#1E1B4B',
    'primary-hover': '#C4B5FD',
    'danger': '#DC2626',
    'danger-foreground': '#FFFFFF',
  },
  radius: 0.5,
}`,
          },
          {
            value: "output",
            label: "결과 base64",
            language: "text",
            filename: "--theme <이 문자열>",
            code: `eyJsaWdodCI6eyJiYWNrZ3JvdW5kIjoiI0ZGRkZGRiIsImJhY2tncm91bmQtc3VidGxlIjoiI0ZBRkFGQSIsImJhY2tncm91bmQtbXV0ZWQiOiIjRjVGNUY1IiwiYmFja2dyb3VuZC1pbnZlcnNlIjoiIzBBMEEwQSIsImZvcmVncm91bmQiOiIjMEEwQTBBIiwiZm9yZWdyb3VuZC1tdXRlZCI6IiM1MjUyNTIiLCJmb3JlZ3JvdW5kLXN1YnRsZSI6IiNBM0EzQTMiLCJmb3JlZ3JvdW5kLWludmVyc2UiOiIjRkZGRkZGIiwiYm9yZGVyIjoiI0U1RTVFNSIsImJvcmRlci1zdHJvbmciOiIjRDRENEQ0IiwicHJpbWFyeSI6IiM3QzNBRUQiLCJwcmltYXJ5LWZvcmVncm91bmQiOiIjRkZGRkZGIiwicHJpbWFyeS1ob3ZlciI6IiM2RDI4RDkiLCJkYW5nZXIiOiIjREMyNjI2IiwiZGFuZ2VyLWZvcmVncm91bmQiOiIjRkZGRkZGIn0sImRhcmsiOnsiYmFja2dyb3VuZCI6IiMwQTBBMEEiLCJiYWNrZ3JvdW5kLXN1YnRsZSI6IiMxNzE3MTciLCJiYWNrZ3JvdW5kLW11dGVkIjoiIzI2MjYyNiIsImJhY2tncm91bmQtaW52ZXJzZSI6IiNGRkZGRkYiLCJmb3JlZ3JvdW5kIjoiI0ZBRkFGQSIsImZvcmVncm91bmQtbXV0ZWQiOiIjQTNBM0EzIiwiZm9yZWdyb3VuZC1zdWJ0bGUiOiIjNzM3MzczIiwiZm9yZWdyb3VuZC1pbnZlcnNlIjoiIzBBMEEwQSIsImJvcmRlciI6IiMyNjI2MjYiLCJib3JkZXItc3Ryb25nIjoiIzQwNDA0MCIsInByaW1hcnkiOiIjQTc4QkZBIiwicHJpbWFyeS1mb3JlZ3JvdW5kIjoiIzFFMUI0QiIsInByaW1hcnktaG92ZXIiOiIjQzRCNUZEIiwiZGFuZ2VyIjoiI0RDMjYyNiIsImRhbmdlci1mb3JlZ3JvdW5kIjoiI0ZGRkZGRiJ9LCJyYWRpdXMiOjAuNX0=`,
          },
        ]}
      />
      <p className="muted">
        15 색 토큰 키는 모두 채워야 통과한다 — 한 키만 빠져도 <code>theme 디코드 실패: light.X 누락</code> 으로 throw. <code>radius</code> 는 0~1.5 (rem) 범위.
      </p>

      <h3>케이스 B — 옵셔널 색 토큰 추가 (success / warning / info)</h3>
      <p>
        상태 색이 필요한 앱(대시보드, 알림 토스트, 폼 검증)이라면 <code>success</code> / <code>warning</code> / <code>info</code> + 각 <code>-foreground</code> 6 키를 light / dark 양쪽에 추가. <strong>한쪽만 정의되면 인코드는 통과하지만 CSS emit 단계에서 빠진다</strong> — 컴포넌트 fallback 보호.
      </p>
      <CodeTabs
        items={[
          {
            value: "input",
            label: "입력 객체",
            language: "ts",
            filename: "encodeTheme(input)",
            code: `{
  light: {
    // ... 케이스 A 의 15 키 그대로 ...
    'success': '#16A34A',  'success-foreground': '#FFFFFF',
    'warning': '#D97706',  'warning-foreground': '#FFFFFF',
    'info':    '#2563EB',  'info-foreground':    '#FFFFFF',
  },
  dark: {
    // ... 케이스 A 의 15 키 그대로 ...
    'success': '#22C55E',  'success-foreground': '#052E16',
    'warning': '#F59E0B',  'warning-foreground': '#1C1917',
    'info':    '#60A5FA',  'info-foreground':    '#0B1A33',
  },
  radius: 0.5,
}`,
          },
          {
            value: "output",
            label: "결과 base64",
            language: "text",
            filename: "--theme <이 문자열>",
            code: `eyJsaWdodCI6eyJiYWNrZ3JvdW5kIjoiI0ZGRkZGRiIsImJhY2tncm91bmQtc3VidGxlIjoiI0ZBRkFGQSIsImJhY2tncm91bmQtbXV0ZWQiOiIjRjVGNUY1IiwiYmFja2dyb3VuZC1pbnZlcnNlIjoiIzBBMEEwQSIsImZvcmVncm91bmQiOiIjMEEwQTBBIiwiZm9yZWdyb3VuZC1tdXRlZCI6IiM1MjUyNTIiLCJmb3JlZ3JvdW5kLXN1YnRsZSI6IiNBM0EzQTMiLCJmb3JlZ3JvdW5kLWludmVyc2UiOiIjRkZGRkZGIiwiYm9yZGVyIjoiI0U1RTVFNSIsImJvcmRlci1zdHJvbmciOiIjRDRENEQ0IiwicHJpbWFyeSI6IiM3QzNBRUQiLCJwcmltYXJ5LWZvcmVncm91bmQiOiIjRkZGRkZGIiwicHJpbWFyeS1ob3ZlciI6IiM2RDI4RDkiLCJkYW5nZXIiOiIjREMyNjI2IiwiZGFuZ2VyLWZvcmVncm91bmQiOiIjRkZGRkZGIiwic3VjY2VzcyI6IiMxNkEzNEEiLCJzdWNjZXNzLWZvcmVncm91bmQiOiIjRkZGRkZGIiwid2FybmluZyI6IiNEOTc3MDYiLCJ3YXJuaW5nLWZvcmVncm91bmQiOiIjRkZGRkZGIiwiaW5mbyI6IiMyNTYzRUIiLCJpbmZvLWZvcmVncm91bmQiOiIjRkZGRkZGIn0sImRhcmsiOnsiYmFja2dyb3VuZCI6IiMwQTBBMEEiLCJiYWNrZ3JvdW5kLXN1YnRsZSI6IiMxNzE3MTciLCJiYWNrZ3JvdW5kLW11dGVkIjoiIzI2MjYyNiIsImJhY2tncm91bmQtaW52ZXJzZSI6IiNGRkZGRkYiLCJmb3JlZ3JvdW5kIjoiI0ZBRkFGQSIsImZvcmVncm91bmQtbXV0ZWQiOiIjQTNBM0EzIiwiZm9yZWdyb3VuZC1zdWJ0bGUiOiIjNzM3MzczIiwiZm9yZWdyb3VuZC1pbnZlcnNlIjoiIzBBMEEwQSIsImJvcmRlciI6IiMyNjI2MjYiLCJib3JkZXItc3Ryb25nIjoiIzQwNDA0MCIsInByaW1hcnkiOiIjQTc4QkZBIiwicHJpbWFyeS1mb3JlZ3JvdW5kIjoiIzFFMUI0QiIsInByaW1hcnktaG92ZXIiOiIjQzRCNUZEIiwiZGFuZ2VyIjoiI0RDMjYyNiIsImRhbmdlci1mb3JlZ3JvdW5kIjoiI0ZGRkZGRiIsInN1Y2Nlc3MiOiIjMjJDNTVFIiwic3VjY2Vzcy1mb3JlZ3JvdW5kIjoiIzA1MkUxNiIsIndhcm5pbmciOiIjRjU5RTBCIiwid2FybmluZy1mb3JlZ3JvdW5kIjoiIzFDMTkxNyIsImluZm8iOiIjNjBBNUZBIiwiaW5mby1mb3JlZ3JvdW5kIjoiIzBCMUEzMyJ9LCJyYWRpdXMiOjAuNX0=`,
          },
        ]}
      />

      <h3>케이스 C — 메트릭 스케일 조정 (spacing / typography)</h3>
      <p>
        컴팩트 UI(정보 밀도 높이기) 또는 큰 폰트(접근성) 처럼 <strong>색은 그대로지만 메트릭만 다른</strong> 톤. <code>spacing</code> / <code>typography</code> / <code>weights</code> / <code>controls</code> / <code>borders</code> / <code>durations</code> 6 카테고리는 모두 <strong>Record&lt;string, number&gt;</strong> 이며 카테고리를 넣으려면 정의된 키를 빠짐없이 채워야 한다 (부분 패치 불가).
      </p>
      <CodeTabs
        items={[
          {
            value: "input",
            label: "입력 객체",
            language: "ts",
            filename: "encodeTheme(input)",
            code: `{
  light: { /* 케이스 A 와 동일 */ },
  dark:  { /* 케이스 A 와 동일 */ },
  radius: 0.5,

  // 컴팩트 spacing — 디폴트 대비 약 0.875× (rem)
  spacing: {
    '0': 0,    '1': 0.125, '2': 0.25, '3': 0.5,  '4': 0.75,
    '5': 1,    '6': 1.25,  '8': 1.75, '10': 2.25, '12': 2.75, '16': 3.75,
  },

  // 본문 15px 기준 타이포 (rem). 다른 카테고리는 생략 → 디폴트 유지.
  typography: {
    'xs': 0.75, 'sm': 0.875, 'base': 0.9375, 'lg': 1.0625,
    'xl': 1.1875, '2xl': 1.4375, '3xl': 1.75, '4xl': 2.125,
  },
}`,
          },
          {
            value: "output",
            label: "결과 base64",
            language: "text",
            filename: "--theme <이 문자열>",
            code: `eyJsaWdodCI6eyJiYWNrZ3JvdW5kIjoiI0ZGRkZGRiIsImJhY2tncm91bmQtc3VidGxlIjoiI0ZBRkFGQSIsImJhY2tncm91bmQtbXV0ZWQiOiIjRjVGNUY1IiwiYmFja2dyb3VuZC1pbnZlcnNlIjoiIzBBMEEwQSIsImZvcmVncm91bmQiOiIjMEEwQTBBIiwiZm9yZWdyb3VuZC1tdXRlZCI6IiM1MjUyNTIiLCJmb3JlZ3JvdW5kLXN1YnRsZSI6IiNBM0EzQTMiLCJmb3JlZ3JvdW5kLWludmVyc2UiOiIjRkZGRkZGIiwiYm9yZGVyIjoiI0U1RTVFNSIsImJvcmRlci1zdHJvbmciOiIjRDRENEQ0IiwicHJpbWFyeSI6IiM3QzNBRUQiLCJwcmltYXJ5LWZvcmVncm91bmQiOiIjRkZGRkZGIiwicHJpbWFyeS1ob3ZlciI6IiM2RDI4RDkiLCJkYW5nZXIiOiIjREMyNjI2IiwiZGFuZ2VyLWZvcmVncm91bmQiOiIjRkZGRkZGIn0sImRhcmsiOnsiYmFja2dyb3VuZCI6IiMwQTBBMEEiLCJiYWNrZ3JvdW5kLXN1YnRsZSI6IiMxNzE3MTciLCJiYWNrZ3JvdW5kLW11dGVkIjoiIzI2MjYyNiIsImJhY2tncm91bmQtaW52ZXJzZSI6IiNGRkZGRkYiLCJmb3JlZ3JvdW5kIjoiI0ZBRkFGQSIsImZvcmVncm91bmQtbXV0ZWQiOiIjQTNBM0EzIiwiZm9yZWdyb3VuZC1zdWJ0bGUiOiIjNzM3MzczIiwiZm9yZWdyb3VuZC1pbnZlcnNlIjoiIzBBMEEwQSIsImJvcmRlciI6IiMyNjI2MjYiLCJib3JkZXItc3Ryb25nIjoiIzQwNDA0MCIsInByaW1hcnkiOiIjQTc4QkZBIiwicHJpbWFyeS1mb3JlZ3JvdW5kIjoiIzFFMUI0QiIsInByaW1hcnktaG92ZXIiOiIjQzRCNUZEIiwiZGFuZ2VyIjoiI0RDMjYyNiIsImRhbmdlci1mb3JlZ3JvdW5kIjoiI0ZGRkZGRiJ9LCJyYWRpdXMiOjAuNSwic3BhY2luZyI6eyIwIjowLCIxIjowLjEyNSwiMiI6MC4yNSwiMyI6MC41LCI0IjowLjc1LCI1IjoxLCI2IjoxLjI1LCI4IjoxLjc1LCIxMCI6Mi4yNSwiMTIiOjIuNzUsIjE2IjozLjc1fSwidHlwb2dyYXBoeSI6eyJ4cyI6MC43NSwic20iOjAuODc1LCJiYXNlIjowLjkzNzUsImxnIjoxLjA2MjUsInhsIjoxLjE4NzUsIjJ4bCI6MS40Mzc1LCIzeGwiOjEuNzUsIjR4bCI6Mi4xMjV9fQ==`,
          },
        ]}
      />
      <p className="muted">
        스칼라 카테고리 전체 키 — <code>spacing</code> 11 키(<code>0~6, 8, 10, 12, 16</code>), <code>typography</code> 8 키(<code>xs~4xl</code>), <code>weights</code> 4 키, <code>controls</code> 3 키(<code>sm/md/lg</code>), <code>borders</code> 2 키(<code>width/widthStrong</code>), <code>durations</code> 3 키(<code>fast/base/slow</code>). 누락 / 추가 키 모두 throw.
      </p>

      <h3>케이스 D — 비주얼 효과 (shadows / eases / gradients)</h3>
      <p>
        그림자 깊이, 모션 곡선, 브랜드 그라디언트까지 손볼 때. 이 3 카테고리는 <strong>Record&lt;string, string&gt;</strong> — CSS 값을 그대로 통과시키므로 <code>cubic-bezier</code> / <code>linear-gradient</code> / multi-shadow 모두 가능.
      </p>
      <CodeTabs
        items={[
          {
            value: "input",
            label: "입력 객체",
            language: "ts",
            filename: "encodeTheme(input)",
            code: `{
  light: { /* 케이스 A 와 동일 */ },
  dark:  { /* 케이스 A 와 동일 */ },
  radius: 0.5,

  // 부드럽고 얕은 그림자 (Linear 풍)
  shadows: {
    'sm': '0 1px 2px 0 rgba(0,0,0,0.04)',
    'md': '0 4px 8px -2px rgba(0,0,0,0.06), 0 2px 4px -2px rgba(0,0,0,0.04)',
    'lg': '0 12px 24px -6px rgba(0,0,0,0.08), 0 4px 8px -4px rgba(0,0,0,0.04)',
    'xl': '0 24px 48px -12px rgba(0,0,0,0.12)',
  },

  // Material expressive 풍 곡선
  eases: {
    'standard':   'cubic-bezier(0.2, 0, 0, 1)',
    'emphasized': 'cubic-bezier(0.3, 0, 0, 1)',
  },

  // 브랜드 그라디언트
  gradients: {
    'primary': 'linear-gradient(135deg, #7C3AED 0%, #EC4899 100%)',
    'surface': 'linear-gradient(180deg, #FFFFFF 0%, #FAFAFA 100%)',
    'overlay': 'linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.4) 100%)',
  },
}`,
          },
          {
            value: "output",
            label: "결과 base64",
            language: "text",
            filename: "--theme <이 문자열>",
            code: `eyJsaWdodCI6eyJiYWNrZ3JvdW5kIjoiI0ZGRkZGRiIsImJhY2tncm91bmQtc3VidGxlIjoiI0ZBRkFGQSIsImJhY2tncm91bmQtbXV0ZWQiOiIjRjVGNUY1IiwiYmFja2dyb3VuZC1pbnZlcnNlIjoiIzBBMEEwQSIsImZvcmVncm91bmQiOiIjMEEwQTBBIiwiZm9yZWdyb3VuZC1tdXRlZCI6IiM1MjUyNTIiLCJmb3JlZ3JvdW5kLXN1YnRsZSI6IiNBM0EzQTMiLCJmb3JlZ3JvdW5kLWludmVyc2UiOiIjRkZGRkZGIiwiYm9yZGVyIjoiI0U1RTVFNSIsImJvcmRlci1zdHJvbmciOiIjRDRENEQ0IiwicHJpbWFyeSI6IiM3QzNBRUQiLCJwcmltYXJ5LWZvcmVncm91bmQiOiIjRkZGRkZGIiwicHJpbWFyeS1ob3ZlciI6IiM2RDI4RDkiLCJkYW5nZXIiOiIjREMyNjI2IiwiZGFuZ2VyLWZvcmVncm91bmQiOiIjRkZGRkZGIn0sImRhcmsiOnsiYmFja2dyb3VuZCI6IiMwQTBBMEEiLCJiYWNrZ3JvdW5kLXN1YnRsZSI6IiMxNzE3MTciLCJiYWNrZ3JvdW5kLW11dGVkIjoiIzI2MjYyNiIsImJhY2tncm91bmQtaW52ZXJzZSI6IiNGRkZGRkYiLCJmb3JlZ3JvdW5kIjoiI0ZBRkFGQSIsImZvcmVncm91bmQtbXV0ZWQiOiIjQTNBM0EzIiwiZm9yZWdyb3VuZC1zdWJ0bGUiOiIjNzM3MzczIiwiZm9yZWdyb3VuZC1pbnZlcnNlIjoiIzBBMEEwQSIsImJvcmRlciI6IiMyNjI2MjYiLCJib3JkZXItc3Ryb25nIjoiIzQwNDA0MCIsInByaW1hcnkiOiIjQTc4QkZBIiwicHJpbWFyeS1mb3JlZ3JvdW5kIjoiIzFFMUI0QiIsInByaW1hcnktaG92ZXIiOiIjQzRCNUZEIiwiZGFuZ2VyIjoiI0RDMjYyNiIsImRhbmdlci1mb3JlZ3JvdW5kIjoiI0ZGRkZGRiJ9LCJyYWRpdXMiOjAuNSwic2hhZG93cyI6eyJzbSI6IjAgMXB4IDJweCAwIHJnYmEoMCwwLDAsMC4wNCkiLCJtZCI6IjAgNHB4IDhweCAtMnB4IHJnYmEoMCwwLDAsMC4wNiksIDAgMnB4IDRweCAtMnB4IHJnYmEoMCwwLDAsMC4wNCkiLCJsZyI6IjAgMTJweCAyNHB4IC02cHggcmdiYSgwLDAsMCwwLjA4KSwgMCA0cHggOHB4IC00cHggcmdiYSgwLDAsMCwwLjA0KSIsInhsIjoiMCAyNHB4IDQ4cHggLTEycHggcmdiYSgwLDAsMCwwLjEyKSJ9LCJlYXNlcyI6eyJzdGFuZGFyZCI6ImN1YmljLWJlemllcigwLjIsIDAsIDAsIDEpIiwiZW1waGFzaXplZCI6ImN1YmljLWJlemllcigwLjMsIDAsIDAsIDEpIn0sImdyYWRpZW50cyI6eyJwcmltYXJ5IjoibGluZWFyLWdyYWRpZW50KDEzNWRlZywgIzdDM0FFRCAwJSwgI0VDNDg5OSAxMDAlKSIsInN1cmZhY2UiOiJsaW5lYXItZ3JhZGllbnQoMTgwZGVnLCAjRkZGRkZGIDAlLCAjRkFGQUZBIDEwMCUpIiwib3ZlcmxheSI6ImxpbmVhci1ncmFkaWVudCgxODBkZWcsIHJnYmEoMCwwLDAsMCkgMCUsIHJnYmEoMCwwLDAsMC40KSAxMDAlKSJ9fQ==`,
          },
        ]}
      />
      <p className="muted">
        문자열 카테고리 키 — <code>shadows</code> 4(<code>sm/md/lg/xl</code>), <code>eases</code> 2(<code>standard/emphasized</code>), <code>gradients</code> 3(<code>primary/surface/overlay</code>). 빈 문자열 또는 512자 초과는 throw. CSS 문법 자체는 inject 단계에서 검증되므로 잘못된 값(예: <code>cubic-bezir(...)</code> 오타)은 인코드 시점엔 통과한다.
      </p>

      <h3>AI 없이 base64 만들기 — 3 경로</h3>
      <p>
        base64 인코더는 <strong>JSON 을 base64 로 바꿔 round-trip 검증</strong>하는 게 전부다 — AI 와 결합되어 있지 않다. 위 케이스 A~D 의 입력 객체를 직접 손으로 짠 뒤, 아래 셋 중 편한 경로로 인코딩하면 산출물은 동일하다.
      </p>
      <CodeTabs
        items={[
          {
            value: "playground",
            label: "/create 플레이그라운드",
            language: "bash",
            filename: "추천 — 시각 편집 + 자동 export",
            code: `# 1. docs 사이트의 /create 페이지 열기
# 2. 토큰 슬라이더/컬러피커로 톤 조정 (라이브 미리보기)
# 3. "프로젝트 생성" 다이얼로그가 아래 명령을 자동 합성:

npx sh-ui-cli create my-app \\
  --platform next --structure standalone \\
  --theme 'eyJsaWdodCI6...'   # ← 자동 생성된 base64

# 사용자는 base64 문자열을 한 번도 보지 않아도 됨.
# 클라이언트 사이드 encodeTheme.ts 가 다이얼로그 안에서 합성.`,
          },
          {
            value: "node",
            label: "Node 한 줄",
            language: "bash",
            filename: "스크립트 / CI 친화",
            code: `# 케이스 A 입력 객체를 그대로 인코드 — JSON.stringify + base64.
# encodeTheme 함수도 round-trip 검증을 더할 뿐 산출물은 동일.

node -e '
const theme = {
  light: { /* §9 케이스 A 의 light 15 키 */ },
  dark:  { /* §9 케이스 A 의 dark 15 키 */ },
  radius: 0.5,
};
console.log(Buffer.from(JSON.stringify(theme)).toString("base64"));
'

# 검증까지 같이:
node -e '
const { encodeTheme } = require("@sh-ui/cli/src/create/theme/encode.js");
console.log(encodeTheme(/* 위 theme */));
'`,
          },
          {
            value: "browser",
            label: "브라우저 콘솔",
            language: "js",
            filename: "DevTools 한 줄",
            code: `// 어느 페이지든 DevTools Console 에 붙여넣기.
// btoa 는 base64 만, 검증은 없음 — sh-ui CLI 가 어차피 디코드 시 검증.
btoa(JSON.stringify({
  light: { /* §9 케이스 A 의 light 15 키 */ },
  dark:  { /* §9 케이스 A 의 dark 15 키 */ },
  radius: 0.5,
}));
// → "eyJsaWdodCI6..."`,
          },
        ]}
      />
      <p className="muted">
        세 경로 모두 같은 base64 를 만든다 — 검증만 더하느냐의 차이. <code>/create</code> 와 Node 의 <code>encodeTheme</code> 은 round-trip 검증 포함, <code>btoa</code> 직접은 검증 없음 (CLI <code>--theme</code> 가 디코드 시점에 어차피 검증). MCP <code>sh_ui_encode_theme</code> 도 내부에서 같은 함수를 호출할 뿐, 별도 마법은 없다.
      </p>

      <h3>케이스 적용 — 새 프로젝트로 그대로 끌고 가기</h3>
      <p>
        위 base64 중 어느 것이든 <code>theme</code> 자리에 그대로:
      </p>
      <CodeTabs
        items={[
          {
            value: "cli",
            label: "CLI",
            language: "bash",
            code: `npx sh-ui-cli create my-app \\
  --platform next --structure standalone \\
  --theme 'eyJsaWdodCI6...'   # ← 위 케이스 중 하나의 base64`,
          },
          {
            value: "mcp",
            label: "MCP create",
            language: "ts",
            code: `// AI 한 턴 안에서 끝낼 때
sh_ui_create_project({
  name: 'my-app',
  platform: 'next',
  structure: 'standalone',
  theme: 'eyJsaWdodCI6...',  // ← 위 케이스 중 하나의 base64
});`,
          },
          {
            value: "round-trip",
            label: "기존 base64 부분 수정",
            language: "ts",
            code: `// primary 만 다른 색으로 갈고 싶을 때
const obj = sh_ui_decode_theme('eyJsaWdodCI6...');  // 케이스 A~D 중 하나
obj.light.primary = '#0EA5E9';
obj.light['primary-hover'] = '#0284C7';
const next = sh_ui_encode_theme(obj);
// next 를 새 sh_ui_create_project 의 theme 에 넘김`,
          },
        ]}
      />

      <h2>다음 단계</h2>
      <ul>
        <li><a href="/tokens">토큰</a> — 덮을 수 있는 전체 변수 목록</li>
        <li><a href="/create">프로젝트 생성</a> — 인터랙티브로 토큰 값 조정하며 미리보기 + 디자인 그대로 새 프로젝트 생성</li>
        <li><a href="/mcp">MCP</a> — <code>sh_ui_encode_theme</code> / <code>sh_ui_decode_theme</code> 툴 상세</li>
      </ul>
    </main>
  );
}
