export const dynamic = "force-static";

import { CodePanel } from "@/components/ui/code-panel";
import { CodeTabs } from "@/components/code-tabs";

export default function ThemingPage() {
  return (
    <main className="container">
      <h1>테마 커스터마이징</h1>
      <p className="muted">
        sh-ui 토큰을 프로젝트에 맞게 바꾸는 방법. 쉬운 것부터 깊이 있는 것까지.
      </p>

      <h2>1. sh-ui.config.json 3축</h2>
      <p>
        가장 가벼운 커스터마이징. <code>base</code>, <code>radius</code>, <code>mode</code> 값을 바꾼 뒤 <code>npx sh-ui-cli add tokens</code>로 재생성하면 전체 토큰이 새 값으로 갱신된다.
      </p>
      <CodePanel
        language="json"
        filename="sh-ui.config.json"
        code={`{
  "theme": {
    "base": "zinc",          // neutral → zinc / slate (grayscale 톤)
    "radius": "lg",          // md → lg (전체 radius 확대)
    "mode": "light-dark"     // 다크 분기 유지
  }
}`}
      />
      <p className="muted">
        base / radius / mode는 <strong>프리셋 스위치</strong>다. 더 세밀한 제어는 아래 방법 사용.
      </p>

      <h2>2. CSS 변수 오버라이드 (React)</h2>
      <p>
        생성된 <code>tokens.css</code>를 직접 열어 필요한 변수만 덮어쓴다. <code>tokens.css</code>는 <strong>당신 것</strong>이다 — shadcn 방식이라 재생성 없이 수정 가능.
      </p>
      <CodePanel
        language="css"
        filename="app/styles/tokens.css"
        code={`:root {
  /* 생성된 값 */
  --primary: #171717;
  --primary-hover: #262626;

  /* 브랜드 컬러로 덮어쓰기 */
  --primary: #7C3AED;         /* Violet 600 */
  --primary-hover: #6D28D9;   /* Violet 700 */
  --primary-foreground: #FFFFFF;
}

.dark {
  --primary: #A78BFA;         /* Violet 400 */
  --primary-hover: #C4B5FD;
}`}
      />
      <p className="muted">
        팁: 생성된 값 바로 아래에 오버라이드를 두면 "어느 것이 원본이고 어느 것이 커스텀인지" 분명해진다.
      </p>

      <h2>3. Flutter ShUiTheme copyWith</h2>
      <p>
        Flutter는 <code>sh_ui_tokens.dart</code>를 직접 수정하거나, <code>MaterialApp</code>에 등록할 때 <code>copyWith</code>로 덮어쓴다. 재생성해도 살아남는 오버라이드를 원하면 <code>copyWith</code>를 권장.
      </p>
      <CodeTabs
        items={[
          {
            value: "copywith",
            label: "copyWith",
            language: "dart",
            filename: "main.dart",
            code: `final customColors = ShUiColorTokens.light.copyWith(
  // light 모드 기본값을 가져온 뒤 primary만 브랜드 컬러로
);

final customLight = ShUiTheme.light.copyWith(
  colors: const ShUiColorTokens(
    background: Color(0xFFFFFFFF),
    backgroundSubtle: Color(0xFFFAFAFA),
    backgroundMuted: Color(0xFFF5F5F5),
    backgroundInverse: Color(0xFF0A0A0A),
    foreground: Color(0xFF0A0A0A),
    foregroundMuted: Color(0xFF737373),
    foregroundSubtle: Color(0xFFA3A3A3),
    foregroundInverse: Color(0xFFFFFFFF),
    border: Color(0xFFE5E5E5),
    borderStrong: Color(0xFFD4D4D4),
    primary: Color(0xFF7C3AED),          // ← 브랜드 컬러
    primaryForeground: Color(0xFFFFFFFF),
    primaryHover: Color(0xFF6D28D9),     // ← 호버
    danger: Color(0xFFEF4444),
    dangerForeground: Color(0xFFFFFFFF),
  ),
);

MaterialApp(
  theme: ThemeData(extensions: [customLight]),
  // ...
);`,
          },
          {
            value: "direct",
            label: "파일 직접 수정",
            language: "dart",
            filename: "lib/foundation/sh_ui_tokens.dart",
            code: `// 주석 "Generated by @sh-ui/tokens" 무시하고 값을 바꾸면 됨.
// 단, 재생성(npx sh-ui-cli add tokens) 시 덮어쓰니 config.json으로
// 관리 가능한 건 1번 방법으로.

static const light = ShUiColorTokens(
  // ...
  primary: Color(0xFF7C3AED),
  primaryHover: Color(0xFF6D28D9),
  // ...
);`,
          },
        ]}
      />

      <h2>4. 스코프 기반 테마 (일부 영역만 다른 색)</h2>
      <p>
        대시보드 안에서 특정 섹션만 다른 primary를 쓰고 싶다면, 부모에 클래스/CSS 변수를 한정해서 토큰을 덮는다.
      </p>
      <CodePanel
        language="css"
        code={`/* tokens.css 또는 컴포넌트 CSS */
.promo-section {
  --primary: #EC4899;           /* 해당 섹션 내부에서만 pink */
  --primary-hover: #DB2777;
  --radius: 1rem;               /* 더 둥근 카드 느낌 */
}`}
      />
      <CodePanel
        language="tsx"
        code={`<div className="promo-section">
  <Button>이벤트 참여하기</Button>    {/* pink primary */}
</div>

<Button>일반 액션</Button>              {/* 원래 primary */}`}
      />
      <p className="muted">
        CSS 변수는 자식에게 캐스케이드된다. 컴포넌트 코드는 한 줄도 수정 안 하고 스코프 내부만 테마가 바뀐다.
      </p>

      <h2>5. 레시피 — 브랜드 컬러 전면 적용</h2>
      <p>
        Violet(보라) 기반 브랜드로 바꾸는 최소 diff.
      </p>
      <CodePanel
        language="css"
        filename="app/styles/tokens.css"
        code={`:root {
  --primary: #7C3AED;
  --primary-hover: #6D28D9;
  --primary-foreground: #FFFFFF;
}
.dark {
  --primary: #A78BFA;
  --primary-hover: #C4B5FD;
  --primary-foreground: #1E1B4B;
}`}
      />

      <h2>6. 레시피 — 컴팩트 UI</h2>
      <p>
        control 높이와 spacing을 한 단계 줄여 정보 밀도 올리기.
      </p>
      <CodePanel
        language="css"
        code={`:root {
  /* 40/32/48 → 36/28/44로 한 단계씩 줄이기 */
  --control-sm: 28px;
  --control-md: 36px;
  --control-lg: 44px;

  /* padding 줄이기 */
  --space-3: 10px;   /* 12 → 10 */
  --space-4: 14px;   /* 16 → 14 */
}`}
      />
      <p className="muted">
        <strong>주의</strong>: 스케일을 통째로 덮으면 이미 해당 토큰을 쓰는 모든 컴포넌트가 영향을 받는다. 특정 컴포넌트만 줄이려면 스코프 방식을 사용.
      </p>

      <h2>7. 레시피 — 커스텀 폰트 스케일</h2>
      <p>
        기본 스케일(12/14/16/18/20/24)이 작다면 전체 한 단계 올리기.
      </p>
      <CodePanel
        language="css"
        code={`:root {
  --text-xs:   13px;
  --text-sm:   15px;
  --text-base: 17px;
  --text-lg:   19px;
  --text-xl:   22px;
  --text-2xl:  26px;
}`}
      />
      <p>
        Flutter에서 같은 변경을 하려면 <code>ShUiTextTokens</code>를 직접 만든 뒤 <code>ShUiTheme.light.copyWith(text: customText)</code>로 끼워 넣는다.
      </p>

      <h2>다음 단계</h2>
      <ul>
        <li><a href="/tokens">토큰</a> — 덮을 수 있는 전체 변수 목록</li>
        <li><a href="/create">프로젝트 생성</a> — 인터랙티브로 토큰 값 조정하며 미리보기 + 디자인 그대로 새 프로젝트 생성</li>
      </ul>
    </main>
  );
}
