// Generated by @sh-ui/tokens — do not edit directly
// base=neutral radius=md mode=light-dark

import 'package:flutter/material.dart';

@immutable
class ShUiColorTokens {
  final Color background;
  final Color backgroundSubtle;
  final Color backgroundMuted;
  final Color backgroundInverse;
  final Color foreground;
  final Color foregroundMuted;
  final Color foregroundSubtle;
  final Color foregroundInverse;
  final Color border;
  final Color borderStrong;
  final Color primary;
  final Color primaryForeground;
  final Color primaryHover;
  final Color danger;
  final Color dangerForeground;

  const ShUiColorTokens({
    required this.background,
    required this.backgroundSubtle,
    required this.backgroundMuted,
    required this.backgroundInverse,
    required this.foreground,
    required this.foregroundMuted,
    required this.foregroundSubtle,
    required this.foregroundInverse,
    required this.border,
    required this.borderStrong,
    required this.primary,
    required this.primaryForeground,
    required this.primaryHover,
    required this.danger,
    required this.dangerForeground,
  });

  // sh-ui:theme-colors-start
  static const light = ShUiColorTokens(
    background: Color(0xFFFFFFFF),
    backgroundSubtle: Color(0xFFFAFAFA),
    backgroundMuted: Color(0xFFF5F5F5),
    backgroundInverse: Color(0xFF0A0A0A),
    foreground: Color(0xFF0A0A0A),
    foregroundMuted: Color(0xFF525252),
    foregroundSubtle: Color(0xFFA3A3A3),
    foregroundInverse: Color(0xFFFFFFFF),
    border: Color(0xFFE5E5E5),
    borderStrong: Color(0xFFD4D4D4),
    primary: Color(0xFF171717),
    primaryForeground: Color(0xFFFAFAFA),
    primaryHover: Color(0xFF262626),
    danger: Color(0xFFDC2626),
    dangerForeground: Color(0xFFFFFFFF),
  );

  static const dark = ShUiColorTokens(
    background: Color(0xFF0A0A0A),
    backgroundSubtle: Color(0xFF171717),
    backgroundMuted: Color(0xFF262626),
    backgroundInverse: Color(0xFFFFFFFF),
    foreground: Color(0xFFFAFAFA),
    foregroundMuted: Color(0xFFA3A3A3),
    foregroundSubtle: Color(0xFF737373),
    foregroundInverse: Color(0xFF0A0A0A),
    border: Color(0xFF262626),
    borderStrong: Color(0xFF404040),
    primary: Color(0xFFFAFAFA),
    primaryForeground: Color(0xFF171717),
    primaryHover: Color(0xFFE5E5E5),
    danger: Color(0xFFDC2626),
    dangerForeground: Color(0xFFFFFFFF),
  );
  // sh-ui:theme-colors-end
}

@immutable
class ShUiRadiusTokens {
  final double defaultRadius;

  const ShUiRadiusTokens({
    required this.defaultRadius,
  });

  static const tokens = ShUiRadiusTokens(
    // sh-ui:theme-radius-start
    defaultRadius: 8.0,
    // sh-ui:theme-radius-end
  );
}

@immutable
class ShUiSpacingTokens {
  final double s0;
  final double s1;
  final double s2;
  final double s3;
  final double s4;
  final double s5;
  final double s6;
  final double s8;
  final double s10;
  final double s12;
  final double s16;

  const ShUiSpacingTokens({
    required this.s0,
    required this.s1,
    required this.s2,
    required this.s3,
    required this.s4,
    required this.s5,
    required this.s6,
    required this.s8,
    required this.s10,
    required this.s12,
    required this.s16,
  });

  static const tokens = ShUiSpacingTokens(
    // sh-ui:theme-space-start
    s0: 0.0,
    s1: 4.0,
    s2: 8.0,
    s3: 12.0,
    s4: 16.0,
    s5: 20.0,
    s6: 24.0,
    s8: 32.0,
    s10: 40.0,
    s12: 48.0,
    s16: 64.0,
    // sh-ui:theme-space-end
  );
}

@immutable
class ShUiTextTokens {
  final double xs;
  final double sm;
  final double base;
  final double lg;
  final double xl;
  final double xl2;
  final double xl3;
  final double xl4;

  const ShUiTextTokens({
    required this.xs,
    required this.sm,
    required this.base,
    required this.lg,
    required this.xl,
    required this.xl2,
    required this.xl3,
    required this.xl4,
  });

  static const tokens = ShUiTextTokens(
    // sh-ui:theme-text-start
    xs: 12.0,
    sm: 14.0,
    base: 16.0,
    lg: 18.0,
    xl: 20.0,
    xl2: 24.0,
    xl3: 30.0,
    xl4: 36.0,
    // sh-ui:theme-text-end
  );
}

@immutable
class ShUiWeightTokens {
  final FontWeight regular;
  final FontWeight medium;
  final FontWeight semibold;
  final FontWeight bold;

  const ShUiWeightTokens({
    required this.regular,
    required this.medium,
    required this.semibold,
    required this.bold,
  });

  static const tokens = ShUiWeightTokens(
    // sh-ui:theme-weight-start
    regular: FontWeight.w400,
    medium: FontWeight.w500,
    semibold: FontWeight.w600,
    bold: FontWeight.w700,
    // sh-ui:theme-weight-end
  );
}

@immutable
class ShUiShadowTokens {
  final List<BoxShadow> sm;
  final List<BoxShadow> md;
  final List<BoxShadow> lg;
  final List<BoxShadow> xl;

  const ShUiShadowTokens({
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
  });

  static const tokens = ShUiShadowTokens(
    // sh-ui:theme-shadow-start
    sm: <BoxShadow>[BoxShadow(offset: Offset(0.0, 1.0), blurRadius: 2.0, spreadRadius: 0.0, color: Color(0x14000000))],
    md: <BoxShadow>[BoxShadow(offset: Offset(0.0, 4.0), blurRadius: 12.0, spreadRadius: 0.0, color: Color(0x1F000000))],
    lg: <BoxShadow>[BoxShadow(offset: Offset(0.0, 8.0), blurRadius: 24.0, spreadRadius: 0.0, color: Color(0x26000000))],
    xl: <BoxShadow>[BoxShadow(offset: Offset(0.0, 16.0), blurRadius: 48.0, spreadRadius: 0.0, color: Color(0x2E000000))],
    // sh-ui:theme-shadow-end
  );
}

@immutable
class ShUiDurationTokens {
  final Duration fast;
  final Duration base;
  final Duration slow;

  const ShUiDurationTokens({
    required this.fast,
    required this.base,
    required this.slow,
  });

  static const tokens = ShUiDurationTokens(
    // sh-ui:theme-duration-start
    fast: Duration(milliseconds: 120),
    base: Duration(milliseconds: 160),
    slow: Duration(milliseconds: 200),
    // sh-ui:theme-duration-end
  );
}

@immutable
class ShUiEaseTokens {
  final Curve standard;
  final Curve emphasized;

  const ShUiEaseTokens({
    required this.standard,
    required this.emphasized,
  });

  static const tokens = ShUiEaseTokens(
    // sh-ui:theme-ease-start
    standard: Cubic(0.4, 0, 0.2, 1),
    emphasized: Cubic(0.2, 0, 0, 1),
    // sh-ui:theme-ease-end
  );
}

@immutable
class ShUiControlTokens {
  final double sm;
  final double md;
  final double lg;

  const ShUiControlTokens({
    required this.sm,
    required this.md,
    required this.lg,
  });

  static const tokens = ShUiControlTokens(
    // sh-ui:theme-control-start
    sm: 32.0,
    md: 40.0,
    lg: 48.0,
    // sh-ui:theme-control-end
  );
}

@immutable
class ShUiBorderWidthTokens {
  final double normal;
  final double strong;

  const ShUiBorderWidthTokens({
    required this.normal,
    required this.strong,
  });

  static const tokens = ShUiBorderWidthTokens(
    // sh-ui:theme-border-width-start
    normal: 1.0,
    strong: 2.0,
    // sh-ui:theme-border-width-end
  );
}

@immutable
class ShUiOpacityTokens {
  final double disabled;

  const ShUiOpacityTokens({
    required this.disabled,
  });

  static const tokens = ShUiOpacityTokens(
    disabled: 0.5,
  );
}

@immutable
class ShUiGradientTokens {
  final LinearGradient primary;
  final LinearGradient surface;
  final LinearGradient overlay;

  const ShUiGradientTokens({
    required this.primary,
    required this.surface,
    required this.overlay,
  });

  static const tokens = ShUiGradientTokens(
    // sh-ui:theme-gradient-start
    primary: LinearGradient(begin: Alignment(-0.707, 0.707), end: Alignment(0.707, -0.707), colors: <Color>[Color(0xFF171717), Color(0xFF525252)], stops: <double>[0.00, 1.00]),
    surface: LinearGradient(begin: Alignment(0.0, -1.0), end: Alignment(0.0, 1.0), colors: <Color>[Color(0xFFFFFFFF), Color(0xFFF5F5F5)], stops: <double>[0.00, 1.00]),
    overlay: LinearGradient(begin: Alignment(0.0, -1.0), end: Alignment(0.0, 1.0), colors: <Color>[Color(0xFF000000), Color(0xFF1F1F1F)], stops: <double>[0.00, 1.00]),
    // sh-ui:theme-gradient-end
  );
}

@immutable
class ShUiBreakpointTokens {
  final double sm;
  final double md;
  final double lg;
  final double xl;

  const ShUiBreakpointTokens({
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
  });

  static const tokens = ShUiBreakpointTokens(
    sm: 640.0,
    md: 768.0,
    lg: 1024.0,
    xl: 1280.0,
  );
}

class ShUiTheme extends ThemeExtension<ShUiTheme> {
  final ShUiColorTokens colors;
  final ShUiRadiusTokens radius;
  final ShUiSpacingTokens spacing;
  final ShUiTextTokens text;
  final ShUiWeightTokens weight;
  final ShUiShadowTokens shadow;
  final ShUiDurationTokens duration;
  final ShUiEaseTokens ease;
  final ShUiControlTokens control;
  final ShUiBorderWidthTokens borderWidth;
  final ShUiGradientTokens gradient;
  final ShUiOpacityTokens opacity;
  final ShUiBreakpointTokens breakpoint;

  const ShUiTheme({
    required this.colors,
    required this.radius,
    required this.spacing,
    required this.text,
    required this.weight,
    required this.shadow,
    required this.duration,
    required this.ease,
    required this.control,
    required this.borderWidth,
    required this.gradient,
    required this.opacity,
    required this.breakpoint,
  });

  static const light = ShUiTheme(
    colors: ShUiColorTokens.light,
    radius: ShUiRadiusTokens.tokens,
    spacing: ShUiSpacingTokens.tokens,
    text: ShUiTextTokens.tokens,
    weight: ShUiWeightTokens.tokens,
    shadow: ShUiShadowTokens.tokens,
    duration: ShUiDurationTokens.tokens,
    ease: ShUiEaseTokens.tokens,
    control: ShUiControlTokens.tokens,
    borderWidth: ShUiBorderWidthTokens.tokens,
    gradient: ShUiGradientTokens.tokens,
    opacity: ShUiOpacityTokens.tokens,
    breakpoint: ShUiBreakpointTokens.tokens,
  );
  static const dark = ShUiTheme(
    colors: ShUiColorTokens.dark,
    radius: ShUiRadiusTokens.tokens,
    spacing: ShUiSpacingTokens.tokens,
    text: ShUiTextTokens.tokens,
    weight: ShUiWeightTokens.tokens,
    shadow: ShUiShadowTokens.tokens,
    duration: ShUiDurationTokens.tokens,
    ease: ShUiEaseTokens.tokens,
    control: ShUiControlTokens.tokens,
    borderWidth: ShUiBorderWidthTokens.tokens,
    gradient: ShUiGradientTokens.tokens,
    opacity: ShUiOpacityTokens.tokens,
    breakpoint: ShUiBreakpointTokens.tokens,
  );

  @override
  ShUiTheme copyWith({ShUiColorTokens? colors, ShUiRadiusTokens? radius, ShUiSpacingTokens? spacing, ShUiTextTokens? text, ShUiWeightTokens? weight, ShUiShadowTokens? shadow, ShUiDurationTokens? duration, ShUiEaseTokens? ease, ShUiControlTokens? control, ShUiBorderWidthTokens? borderWidth, ShUiGradientTokens? gradient, ShUiOpacityTokens? opacity, ShUiBreakpointTokens? breakpoint}) =>
      ShUiTheme(colors: colors ?? this.colors, radius: radius ?? this.radius, spacing: spacing ?? this.spacing, text: text ?? this.text, weight: weight ?? this.weight, shadow: shadow ?? this.shadow, duration: duration ?? this.duration, ease: ease ?? this.ease, control: control ?? this.control, borderWidth: borderWidth ?? this.borderWidth, gradient: gradient ?? this.gradient, opacity: opacity ?? this.opacity, breakpoint: breakpoint ?? this.breakpoint);

  @override
  ShUiTheme lerp(ThemeExtension<ShUiTheme>? other, double t) {
    if (other is! ShUiTheme) return this;
    return t < 0.5 ? this : other;
  }
}
