#!/usr/bin/env node
/**
 * @sh-ui/tokens 빌드 스크립트
 *
 * primitives.json + semantic.json + sh-ui.config.json
 *   → tokens.css  (React / 웹)
 *   → tokens.dart (Flutter)
 *
 * 처리: {base}·{radius} 치환 → {color.neutral.950} 참조 해석 → 플랫폼별 포맷 출력.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "../..");

function getPath(obj, path) {
  return path.split(".").reduce((acc, key) => (acc == null ? acc : acc[key]), obj);
}

function resolveString(str, primitives, context, depth = 0) {
  if (depth > 10) throw new Error(`순환 참조 의심: ${str}`);
  let out = str.replace(/\{([a-zA-Z_][a-zA-Z0-9_]*)\}/g, (m, k) =>
    k in context ? context[k] : m,
  );
  out = out.replace(/\{([a-zA-Z0-9_.]+)\}/g, (m, path) => {
    const node = getPath(primitives, path);
    if (node && typeof node === "object" && "$value" in node) return String(node.$value);
    if (typeof node === "string" || typeof node === "number") return String(node);
    throw new Error(`해석 실패: ${m}`);
  });
  if (/\{[^}]+\}/.test(out)) return resolveString(out, primitives, context, depth + 1);
  return out;
}

function flatten(obj, primitives, context, prefix = []) {
  const result = {};
  for (const [key, node] of Object.entries(obj)) {
    if (key.startsWith("$")) continue;
    if (node && typeof node === "object" && "$value" in node) {
      result[[...prefix, key].join(".")] = resolveString(String(node.$value), primitives, context);
    } else if (node && typeof node === "object") {
      Object.assign(result, flatten(node, primitives, context, [...prefix, key]));
    }
  }
  return result;
}

/** 설정으로 semantic을 해석해 { light, dark, radius } 평탄 맵 반환 */
async function resolveTokens(config) {
  const primitives = JSON.parse(
    await readFile(resolve(__dirname, "src/primitives.json"), "utf8"),
  );
  const semantic = JSON.parse(
    await readFile(resolve(__dirname, "src/semantic.json"), "utf8"),
  );
  const ctx = { base: config.theme.base, radius: config.theme.radius };
  return {
    light: flatten(semantic.light, primitives, ctx),
    dark: flatten(semantic.dark, primitives, ctx),
    radius: flatten(semantic.radius, primitives, ctx, ["radius"]),
  };
}

/* ───────── CSS ───────── */

function toCssVar(path) {
  const parts = path.split(".");
  if (parts[parts.length - 1] === "default") parts.pop();
  return `--${parts.join("-")}`;
}

function emitCssBlock(selector, entries) {
  const lines = Object.entries(entries)
    .map(([p, v]) => `  ${toCssVar(p)}: ${v};`)
    .join("\n");
  return `${selector} {\n${lines}\n}`;
}

export async function buildTokensCss(config) {
  const { light, dark, radius } = await resolveTokens(config);
  const mode = config.theme.mode;
  const blocks = [];
  if (mode === "light" || mode === "light-dark") {
    blocks.push(emitCssBlock(":root", { ...light, ...radius }));
  }
  if (mode === "dark") {
    blocks.push(emitCssBlock(":root", { ...dark, ...radius }));
  }
  if (mode === "light-dark") {
    blocks.push(emitCssBlock(".dark", dark));
  }
  const header = `/* Generated by @sh-ui/tokens — do not edit directly */\n/* base=${config.theme.base} radius=${config.theme.radius} mode=${config.theme.mode} */\n`;
  return header + "\n" + blocks.join("\n\n") + "\n";
}

/* ───────── Dart ───────── */

/** "background.default" → "background", "primary.foreground" → "primaryForeground" */
function toDartField(path) {
  const parts = path.split(".");
  if (parts[parts.length - 1] === "default") parts.pop();
  return parts
    .map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1)))
    .join("");
}

/** "#RRGGBB" → "0xFFRRGGBB", "#RRGGBBAA" → "0xAARRGGBB" */
function hexToDartColor(hex) {
  const m = /^#([0-9a-fA-F]{6})([0-9a-fA-F]{2})?$/.exec(hex);
  if (!m) throw new Error(`지원하지 않는 색상 포맷: ${hex}`);
  const rgb = m[1].toUpperCase();
  const a = (m[2] || "FF").toUpperCase();
  return `Color(0x${a}${rgb})`;
}

/** "0.5rem" → 8.0, "16px" → 16.0, "0px" → 0.0, "9999px" → 9999.0 */
function dimensionToDart(value) {
  const rem = /^(-?\d*\.?\d+)rem$/.exec(value);
  if (rem) return (parseFloat(rem[1]) * 16).toFixed(1);
  const px = /^(-?\d*\.?\d+)px$/.exec(value);
  if (px) return parseFloat(px[1]).toFixed(1);
  throw new Error(`지원하지 않는 치수 포맷: ${value}`);
}

/** 색/radius 평탄 맵을 "field: literal" 줄 배열로 */
function emitDartFields(colorMap, radiusMap) {
  const colorLines = Object.entries(colorMap).map(
    ([p, v]) => `    ${toDartField(p)}: ${hexToDartColor(v)},`,
  );
  const radiusLines = Object.entries(radiusMap).map(([p, v]) => {
    // "radius.default" → defaultRadius (기본 필드는 예약어 회피)
    const parts = p.split(".");
    const tail = parts[parts.length - 1];
    const field = tail === "default" ? "defaultRadius" : toDartField(p.replace(/^radius\./, ""));
    return `    ${field}: ${dimensionToDart(v)},`;
  });
  return { colorLines, radiusLines };
}

export async function buildTokensDart(config) {
  const { light, dark, radius } = await resolveTokens(config);
  const colorFields = Object.keys(light).map(toDartField);
  const radiusFields = Object.keys(radius).map((p) =>
    p === "radius.default" ? "defaultRadius" : toDartField(p.replace(/^radius\./, "")),
  );

  const lightEmit = emitDartFields(light, radius);
  const darkEmit = emitDartFields(dark, radius);

  const colorClass = `@immutable
class ShUiColorTokens {
${colorFields.map((f) => `  final Color ${f};`).join("\n")}

  const ShUiColorTokens({
${colorFields.map((f) => `    required this.${f},`).join("\n")}
  });

  static const light = ShUiColorTokens(
${lightEmit.colorLines.join("\n")}
  );

  static const dark = ShUiColorTokens(
${darkEmit.colorLines.join("\n")}
  );
}`;

  const radiusClass = `@immutable
class ShUiRadiusTokens {
${radiusFields.map((f) => `  final double ${f};`).join("\n")}

  const ShUiRadiusTokens({
${radiusFields.map((f) => `    required this.${f},`).join("\n")}
  });

  static const tokens = ShUiRadiusTokens(
${lightEmit.radiusLines.join("\n")}
  );
}`;

  const themeClass = `class ShUiTheme extends ThemeExtension<ShUiTheme> {
  final ShUiColorTokens colors;
  final ShUiRadiusTokens radius;

  const ShUiTheme({required this.colors, required this.radius});

  static const light = ShUiTheme(colors: ShUiColorTokens.light, radius: ShUiRadiusTokens.tokens);
  static const dark  = ShUiTheme(colors: ShUiColorTokens.dark,  radius: ShUiRadiusTokens.tokens);

  @override
  ShUiTheme copyWith({ShUiColorTokens? colors, ShUiRadiusTokens? radius}) =>
      ShUiTheme(colors: colors ?? this.colors, radius: radius ?? this.radius);

  @override
  ShUiTheme lerp(ThemeExtension<ShUiTheme>? other, double t) {
    if (other is! ShUiTheme) return this;
    return t < 0.5 ? this : other;
  }
}`;

  const header = `// Generated by @sh-ui/tokens — do not edit directly
// base=${config.theme.base} radius=${config.theme.radius} mode=${config.theme.mode}

import 'package:flutter/material.dart';
`;

  return `${header}\n${colorClass}\n\n${radiusClass}\n\n${themeClass}\n`;
}

/* ───────── CLI ───────── */

if (import.meta.url === `file://${process.argv[1]}`) {
  const configPath = resolve(REPO_ROOT, "sh-ui.config.example.json");
  const config = JSON.parse(await readFile(configPath, "utf8"));
  const outDir = resolve(__dirname, "dist");
  await mkdir(outDir, { recursive: true });

  const css = await buildTokensCss(config);
  const cssPath = resolve(outDir, "tokens.css");
  await writeFile(cssPath, css, "utf8");
  console.log(`✓ ${cssPath}`);

  const dart = await buildTokensDart(config);
  const dartPath = resolve(outDir, "sh_ui_tokens.dart");
  await writeFile(dartPath, dart, "utf8");
  console.log(`✓ ${dartPath}`);
}
