// Generated by @hyeon/tokens — do not edit directly
// base=neutral radius=md mode=light-dark
//
// 현재는 스텁(수동 작성). 추후 packages/tokens/build.mjs의 Flutter 타깃이
// hyeon.config.json을 읽어 이 파일을 자동 생성한다.

import 'package:flutter/material.dart';

@immutable
class HyeonColorTokens {
  final Color background;
  final Color backgroundSubtle;
  final Color backgroundMuted;
  final Color foreground;
  final Color foregroundMuted;
  final Color border;
  final Color primary;
  final Color primaryForeground;
  final Color primaryHover;
  final Color danger;
  final Color dangerForeground;

  const HyeonColorTokens({
    required this.background,
    required this.backgroundSubtle,
    required this.backgroundMuted,
    required this.foreground,
    required this.foregroundMuted,
    required this.border,
    required this.primary,
    required this.primaryForeground,
    required this.primaryHover,
    required this.danger,
    required this.dangerForeground,
  });

  static const light = HyeonColorTokens(
    background:        Color(0xFFFFFFFF),
    backgroundSubtle:  Color(0xFFFAFAFA),
    backgroundMuted:   Color(0xFFF5F5F5),
    foreground:        Color(0xFF0A0A0A),
    foregroundMuted:   Color(0xFF737373),
    border:            Color(0xFFE5E5E5),
    primary:           Color(0xFF171717),
    primaryForeground: Color(0xFFFAFAFA),
    primaryHover:      Color(0xFF262626),
    danger:            Color(0xFFEF4444),
    dangerForeground:  Color(0xFFFFFFFF),
  );

  static const dark = HyeonColorTokens(
    background:        Color(0xFF0A0A0A),
    backgroundSubtle:  Color(0xFF171717),
    backgroundMuted:   Color(0xFF262626),
    foreground:        Color(0xFFFAFAFA),
    foregroundMuted:   Color(0xFFA3A3A3),
    border:            Color(0xFF262626),
    primary:           Color(0xFFFAFAFA),
    primaryForeground: Color(0xFF171717),
    primaryHover:      Color(0xFFE5E5E5),
    danger:            Color(0xFFDC2626),
    dangerForeground:  Color(0xFFFFFFFF),
  );
}

@immutable
class HyeonRadiusTokens {
  final double defaultRadius;
  const HyeonRadiusTokens({required this.defaultRadius});

  static const tokens = HyeonRadiusTokens(defaultRadius: 8.0); // md = 0.5rem
}

/// ThemeExtension으로 등록해 Theme.of(context).extension<HyeonTheme>()로 접근한다.
class HyeonTheme extends ThemeExtension<HyeonTheme> {
  final HyeonColorTokens colors;
  final HyeonRadiusTokens radius;

  const HyeonTheme({required this.colors, required this.radius});

  static const light = HyeonTheme(
    colors: HyeonColorTokens.light,
    radius: HyeonRadiusTokens.tokens,
  );
  static const dark = HyeonTheme(
    colors: HyeonColorTokens.dark,
    radius: HyeonRadiusTokens.tokens,
  );

  @override
  HyeonTheme copyWith({HyeonColorTokens? colors, HyeonRadiusTokens? radius}) =>
      HyeonTheme(colors: colors ?? this.colors, radius: radius ?? this.radius);

  @override
  HyeonTheme lerp(ThemeExtension<HyeonTheme>? other, double t) {
    if (other is! HyeonTheme) return this;
    return t < 0.5 ? this : other;
  }
}
