// Generated by @sh-ui/tokens — do not edit directly
// base=neutral radius=md mode=light-dark
//
// 현재는 스텁(수동 작성). 추후 packages/tokens/build.mjs의 Flutter 타깃이
// sh-ui.config.json을 읽어 이 파일을 자동 생성한다.

import 'package:flutter/material.dart';

@immutable
class ShUiColorTokens {
  final Color background;
  final Color backgroundSubtle;
  final Color backgroundMuted;
  final Color foreground;
  final Color foregroundMuted;
  final Color border;
  final Color primary;
  final Color primaryForeground;
  final Color primaryHover;
  final Color danger;
  final Color dangerForeground;

  const ShUiColorTokens({
    required this.background,
    required this.backgroundSubtle,
    required this.backgroundMuted,
    required this.foreground,
    required this.foregroundMuted,
    required this.border,
    required this.primary,
    required this.primaryForeground,
    required this.primaryHover,
    required this.danger,
    required this.dangerForeground,
  });

  static const light = ShUiColorTokens(
    background:        Color(0xFFFFFFFF),
    backgroundSubtle:  Color(0xFFFAFAFA),
    backgroundMuted:   Color(0xFFF5F5F5),
    foreground:        Color(0xFF0A0A0A),
    foregroundMuted:   Color(0xFF737373),
    border:            Color(0xFFE5E5E5),
    primary:           Color(0xFF171717),
    primaryForeground: Color(0xFFFAFAFA),
    primaryHover:      Color(0xFF262626),
    danger:            Color(0xFFEF4444),
    dangerForeground:  Color(0xFFFFFFFF),
  );

  static const dark = ShUiColorTokens(
    background:        Color(0xFF0A0A0A),
    backgroundSubtle:  Color(0xFF171717),
    backgroundMuted:   Color(0xFF262626),
    foreground:        Color(0xFFFAFAFA),
    foregroundMuted:   Color(0xFFA3A3A3),
    border:            Color(0xFF262626),
    primary:           Color(0xFFFAFAFA),
    primaryForeground: Color(0xFF171717),
    primaryHover:      Color(0xFFE5E5E5),
    danger:            Color(0xFFDC2626),
    dangerForeground:  Color(0xFFFFFFFF),
  );
}

@immutable
class ShUiRadiusTokens {
  final double defaultRadius;
  const ShUiRadiusTokens({required this.defaultRadius});

  static const tokens = ShUiRadiusTokens(defaultRadius: 8.0); // md = 0.5rem
}

/// ThemeExtension으로 등록해 Theme.of(context).extension<ShUiTheme>()로 접근한다.
class ShUiTheme extends ThemeExtension<ShUiTheme> {
  final ShUiColorTokens colors;
  final ShUiRadiusTokens radius;

  const ShUiTheme({required this.colors, required this.radius});

  static const light = ShUiTheme(
    colors: ShUiColorTokens.light,
    radius: ShUiRadiusTokens.tokens,
  );
  static const dark = ShUiTheme(
    colors: ShUiColorTokens.dark,
    radius: ShUiRadiusTokens.tokens,
  );

  @override
  ShUiTheme copyWith({ShUiColorTokens? colors, ShUiRadiusTokens? radius}) =>
      ShUiTheme(colors: colors ?? this.colors, radius: radius ?? this.radius);

  @override
  ShUiTheme lerp(ThemeExtension<ShUiTheme>? other, double t) {
    if (other is! ShUiTheme) return this;
    return t < 0.5 ? this : other;
  }
}
